@baseUrl = http://127.0.0.1:8000

# https://kenslearningcurve.com/tutorials/test-an-api-by-using-http-files-in-vscode/

### GET root / index
{{baseUrl}}/


### GET feature weights
{{baseUrl}}/weights/


### HIGH probability of churn (staff will)
POST {{baseUrl}}/predict
Content-Type: application/json

{
    "business_travel": "Frequent Traveller",
    "department": "Human Resources",
    "education_field": "Business Studies",
    "education_level": 5,
    "environment_satisfaction_level": 5,
    "ethnicity": "Black or African American",
    "job_satisfaction_level": 1,
    "manager_rating_level": 4,
    "marital_status": "Single",
    "over_time": 1,
    "relationship_satisfaction_level": 3,
    "self_rating_level": 5,
    "state": "CA",
    "work_life_balance_level": 3,
    "years_since_hire": 10
}

### TEST Validation Fail
POST {{baseUrl}}/predict
Content-Type: application/json

{
    "state": "<invalid>"
}

### TEST discrete
POST {{baseUrl}}/predict
Content-Type: application/json

{
    "state": "CA"
}


### TEST empty
POST {{baseUrl}}/predict
Content-Type: application/json

{}


#
#
#
#
#
#
#
#

### POSITIVE decision of churn (staff will)
POST {{baseUrl}}/decide
Content-Type: application/json

{
    "age": 72
}


### CUSTOM threshold for decision of churn
POST {{baseUrl}}/decide?threshold=0.8
Content-Type: application/json

{
    "age": 72
}


### CUSTOM threshold for decision of churn
POST {{baseUrl}}/decide?threshold=0.8
Content-Type: application/json

{
    "age": 72
}

#
#
#
#
#
#
#

### LOW probability of churn (customer won't)
POST {{baseUrl}}/predict
Content-Type: application/json

{
    "age": 57,
    "job": "blue-collar",
    "marital": "married",
    "education": "primary",
    "balance": 856,
    "housing": "no",
    "contact": "cellular",
    "day": 11,
    "month": "aug",
    "duration": 194,
    "campaign": 6,
    "pdays": -1,
    "previous": 0,
    "poutcome": "unknown"
}


### HIGH probability of churn (customer will)
POST {{baseUrl}}/predict
Content-Type: application/json

{
    "age": 72,
    "job": "retired",
    "marital": "married",
    "education": "primary",
    "balance": 5816,
    "housing": "no",
    "contact": "cellular",
    "day": 11,
    "month": "aug",
    "duration": 1144,
    "campaign": 5,
    "pdays": 184,
    "previous": 3,
    "poutcome": "unknown"
}



### NEGATIVE decision of churn (customer won't)
POST {{baseUrl}}/decide
Content-Type: application/json

{
    "age": 57,
    "job": "blue-collar",
    "marital": "married",
    "education": "primary",
    "balance": 856,
    "housing": "no",
    "contact": "cellular",
    "day": 11,
    "month": "aug",
    "duration": 194,
    "campaign": 6,
    "pdays": -1,
    "previous": 0,
    "poutcome": "unknown"
}


### POSITIVE decision of churn (customer will)
POST {{baseUrl}}/decide
Content-Type: application/json

{
    "age": 72,
    "job": "retired",
    "marital": "married",
    "education": "primary",
    "balance": 5816,
    "housing": "no",
    "contact": "cellular",
    "day": 11,
    "month": "aug",
    "duration": 1144,
    "campaign": 5,
    "pdays": 184,
    "previous": 3,
    "poutcome": "unknown"
}


### CUSTOM threshold for decision of churn
POST {{baseUrl}}/decide?threshold=0.8
Content-Type: application/json

{
    "age": 72,
    "job": "retired",
    "marital": "married",
    "education": "primary",
    "balance": 5816,
    "housing": "no",
    "contact": "cellular",
    "day": 11,
    "month": "aug",
    "duration": 1144,
    "campaign": 5,
    "pdays": 184,
    "previous": 3,
    "poutcome": "unknown"
}